const dummyConcerts = [
  {
    id: 1,
    name: "Eason Chan Live",
    concertDateTime: "2025-11-01",
    venue: "AsiaWorld-Expo",
    price: 300,
    description: "Join Eason Chan for a night of unforgettable hits.",
    availableTickets: 500,
  },
  {
    id: 2,
    name: "Gigi Leung Acoustic Night",
    concertDateTime: "2023-11-15",
    venue: "Hong Kong Convention and Exhibition Centre",
    price: 250,
    description: "An intimate acoustic evening with Gigi Leung.",
    availableTickets: 200,
  },
  {
    id: 3,
    name: "Jacky Cheung World Tour",
    concertDateTime: "2023-12-10",
    venue: "Hong Kong Coliseum",
    price: 400,
    description: "Experience the legendary Jacky Cheung live in concert.",
    availableTickets: 800,
  },
  {
    id: 4,
    name: "Faye Wong Reunion Concert",
    concertDateTime: "2024-01-05",
    venue: "AsiaWorld-Expo",
    price: 350,
    description: "A special reunion concert featuring Faye Wong.",
    availableTickets: 600,
  },
  {
    id: 5,
    name: "Andy Lau Charity Concert",
    concertDateTime: "2024-02-20",
    venue: "Kowloon Bay International Trade & Exhibition Centre",
    price: 280,
    description: "Join Andy Lau for a night of music and charity.",
    availableTickets: 300,
  },
  {
    id: 6,
    name: "Sammi Cheng's 25th Anniversary Concert",
    concertDateTime: "2024-03-15",
    venue: "Hong Kong Coliseum",
    price: 320,
    description: "Celebrating 25 years of music with Sammi Cheng.",
    availableTickets: 500,
  },
  {
    id: 7,
    name: "Joey Yung Live in Hong Kong",
    concertDateTime: "2024-04-10",
    venue: "Hong Kong Convention and Exhibition Centre",
    price: 260,
    description: "A spectacular night with Joey Yung's greatest hits.",
    availableTickets: 400,
  },
  {
    id: 8,
    name: "Hins Cheung World Tour",
    concertDateTime: "2024-05-05",
    venue: "AsiaWorld-Expo",
    price: 290,
    description: "Catch Hins Cheung live as he performs his latest album.",
    availableTickets: 350,
  },
  {
    id: 9,
    name: "Leo Ku's Concert",
    concertDateTime: "2024-06-12",
    venue: "Kowloon Bay International Trade & Exhibition Centre",
    price: 310,
    description: "Enjoy a night filled with Leo Ku's classic hits.",
    availableTickets: 450,
  },
];

export default dummyConcerts;